###
POST  http://localhost:5000/users/register
Content-Type: application/json

{
 "firstName": "BioRegs",
 "lastName": "BioRegs",
 "email" : "bioregisc@gmail.com",
 "password" : "bioreg2020$",
 "passwordCheck" : "bioreg2020$"
}
###
POST  http://localhost:5000/users/login
Content-Type: application/json

{
 "email" : "bioreginc@gmail.com",
 "password" : "bioreg2020$"
}